name: CI

on:
  push:
    branches:
      - main
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron: '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['16', '18', '20']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}

      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
