name: CI

on:
  push:
    branches:
      - main
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron: '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['16', '18', '20']
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install VSCode
        run: |
          wget "https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal"  --output-document=out.zip
          sudo unzip -o out.zip -d /Applications/
      - name: npm install
        run: npm install
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: stefanpenner
      - name: npm test
        run: DEBUG=pw:* npm test
